name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Clone repository code
        run: |
          git clone --branch v4 https://github.com/amannn/action-semantic-pull-request.git ./test/semantic-pull-request
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - uses: ./test/semantic-pull-request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
