name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

  check:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: ./semantic-pull-request